spring.application.name=sport
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sport}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:2134}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ===== Server =====
server.port=${PORT:8080}
server.servlet.context-path=/api
python.path=py